on: [push, pull_request]

jobs:
  check_java_latest:
    runs-on: ubuntu-latest
    name: Java 17
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-jdk17-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-jdk17
            
      - name: Compile with Gradle
        run: ./gradlew assemble
  
      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        if: always() && env.SLACK_WEBHOOK_URL
        with:
          status: custom
          job_name: Java 17
          author_name: Java 17 Build
          fields: workflow,commit,repo,author,took
          # see https://action-slack.netlify.app/usecase/02-custom for custom payload info
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_WORKFLOW} -- (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${{ github.head_ref || github.ref }} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  
  check_java11:
    runs-on: ubuntu-latest
    name: Java 11
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'

      - name: Gradle cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-jdk11-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-jdk11
            
      - name: Compile with Gradle
        run: ./gradlew assemble
  
      - name: Test
        run: ./gradlew check
  
      - name: Code coverage
        uses: codecov/codecov-action@v3

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        if: always() && env.SLACK_WEBHOOK_URL
        with:
          status: custom
          job_name: Java 11
          author_name: Java 11 Build/Test
          fields: workflow,commit,repo,author,took
          # see https://action-slack.netlify.app/usecase/02-custom for custom payload info
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_WORKFLOW} -- (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${{ github.head_ref || github.ref }} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
